import path from "node:path";
import type { FileEntry, ResolvedConfig } from "./types.js";

/**
 * Default banner prepended to every generated map, unless overridden via
 * `config.header`. Wording explicitly tells humans not to edit the file
 * by hand and points them at the regeneration command.
 */
const DEFAULT_HEADER = [
  "# Repo Map",
  "",
  "_Auto-generated by [coderunes](https://www.npmjs.com/package/coderunes). Do not edit by hand. Run `npm run build:map` to refresh._",
].join("\n");

/**
 * Renders a sorted list of {@link FileEntry} into the final REPO_MAP markdown.
 *
 * Output is deterministic and ends with exactly one trailing newline so
 * `--check` produces stable diffs.
 *
 * @param entries  Per-file extraction results. Files with zero signatures
 *                 are dropped here, not by the caller.
 * @param config   Resolved config. Only `header` and `groupByDirectory` affect
 *                 rendering; all other fields are passed through for context.
 */
export function render(entries: FileEntry[], config: ResolvedConfig): string {
  const lines: string[] = [];
  lines.push(config.header ?? DEFAULT_HEADER);
  lines.push("");

  // Drop empty entries and sort alphabetically — sorting is what makes the
  // output deterministic across filesystems with different readdir orderings.
  const filtered = entries.filter((e) => e.signatures.length > 0);
  filtered.sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : 0));

  if (config.groupByDirectory) {
    let currentDir: string | null = null;

    for (const entry of filtered) {
      const dir = path.posix.dirname(entry.file);
      const dirLabel = dir === "." ? "(root)" : dir;

      // Only emit a directory header when we cross into a new directory.
      if (dirLabel !== currentDir) {
        lines.push(`## ${dirLabel}`);
        lines.push("");
        currentDir = dirLabel;
      }

      appendEntry(lines, entry);
    }
  } else {
    for (const entry of filtered) {
      appendEntry(lines, entry);
    }
  }

  // Collapse any trailing blank lines, then guarantee exactly one newline.
  return lines.join("\n").replace(/\n+$/, "") + "\n";
}

/**
 * Pushes the markdown for a single file entry onto the lines buffer.
 * Always followed by a blank line so files render as visually separate blocks.
 */
function appendEntry(lines: string[], entry: FileEntry): void {
  lines.push(`### ${entry.file}`);

  if (entry.summary) {
    lines.push(`_${entry.summary}_`);
  }

  for (const sig of entry.signatures) {
    lines.push(`- \`${sig}\``);
  }

  lines.push("");
}
