import path from "node:path";
import type { FileEntry, ResolvedConfig } from "./types.js";

const DEFAULT_HEADER = [
  "# Repo Map",
  "",
  "_Auto-generated by [coderunes](https://www.npmjs.com/package/coderunes). Do not edit by hand. Run `npm run build:map` to refresh._",
].join("\n");

export function render(entries: FileEntry[], config: ResolvedConfig): string {
  const lines: string[] = [];
  lines.push(config.header ?? DEFAULT_HEADER);
  lines.push("");

  const filtered = entries.filter((e) => e.signatures.length > 0);
  filtered.sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : 0));

  if (config.groupByDirectory) {
    let currentDir: string | null = null;
    for (const entry of filtered) {
      const dir = path.posix.dirname(entry.file);
      const dirLabel = dir === "." ? "(root)" : dir;
      if (dirLabel !== currentDir) {
        lines.push(`## ${dirLabel}`);
        lines.push("");
        currentDir = dirLabel;
      }
      appendEntry(lines, entry);
    }
  } else {
    for (const entry of filtered) {
      appendEntry(lines, entry);
    }
  }

  return lines.join("\n").replace(/\n+$/, "") + "\n";
}

function appendEntry(lines: string[], entry: FileEntry): void {
  lines.push(`### ${entry.file}`);
  if (entry.summary) {
    lines.push(`_${entry.summary}_`);
  }
  for (const sig of entry.signatures) {
    lines.push(`- \`${sig}\``);
  }
  lines.push("");
}
